on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet format --verify-no-changes ./src/HotelPosSystem.sln
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet tool install --global dotnet-ef
      - run: dotnet build -c Release ./src/HotelPosSystem.sln
      - run: dotnet test ./src/HotelPosSystem.sln
